[package]
name = "loaded"
version = "0.1.0"
edition = "2024"

[dependencies]
widestring = "1.1.0"
windows = { version = "0.62", features = [
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Threading",
    "Win32_Foundation",
] }
